info:
 company: rain

spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/avatar
  username: root
  password: 123456
  filters: stat
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
 cache:
  custom-type: avatarCache
  enableL1Cache: true
  enableL2Cache: true
  jcache:
   config: classpath:ehcache.xml

 redis:
  host: 127.0.0.1
  port: 6379
  database: 1
  pool:
   min-idle: 0
   max-idle: 8
   max-active: 8
   max-wait: 5000

---
spring:
 profiles: dev1
 application:
   name: avatar-im

info:
 name: avatar-im1

server:
 port: 8101

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8001/eureka
 instance:
  metadataMap:
   instanceId: ${spring.application.name}:${server.port}
   # 在eureka上显示此微服务的ip地址
   prefer-ip-address: true

---
spring:
 profiles: dev2
 application:
  name: avatar-im

info:
 name: avatar-im2

server:
 port: 8102

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8001/eureka
 instance:
  metadataMap:
   instanceId: ${spring.application.name}:${server.port}
   # 在eureka上显示此微服务的ip地址
   prefer-ip-address: true