info:
 name: avatar-order
 company: rain

spring:
 application:
  name: avatar-order
 output:
   ansi:
     enabled: always

server:
 port: 8111

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8001/eureka
 instance:
  metadataMap:
   instanceId: ${spring.application.name}:${server.port}
  # 在eureka上显示此微服务的ip地址
   prefer-ip-address: true