// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFile/BaseFrame.proto

package microavatar.framework.base.protobuf;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FrameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 c2sId = 1;
    boolean hasC2SId();
    long getC2SId();
    
    // optional int64 s2cId = 2;
    boolean hasS2CId();
    long getS2CId();
    
    // optional string javaProtobufClassC2S = 3;
    boolean hasJavaProtobufClassC2S();
    String getJavaProtobufClassC2S();
    
    // optional string javaProtobufClassS2C = 4;
    boolean hasJavaProtobufClassS2C();
    String getJavaProtobufClassS2C();
    
    // optional bytes payload = 5;
    boolean hasPayload();
    com.google.protobuf.ByteString getPayload();
  }
  public static final class Frame extends
      com.google.protobuf.GeneratedMessage
      implements FrameOrBuilder {
    // Use Frame.newBuilder() to construct.
    private Frame(Builder builder) {
      super(builder);
    }
    private Frame(boolean noInit) {}
    
    private static final Frame defaultInstance;
    public static Frame getDefaultInstance() {
      return defaultInstance;
    }
    
    public Frame getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return microavatar.framework.base.protobuf.Base.internal_static_Platform_Model_Frame_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return microavatar.framework.base.protobuf.Base.internal_static_Platform_Model_Frame_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 c2sId = 1;
    public static final int C2SID_FIELD_NUMBER = 1;
    private long c2SId_;
    public boolean hasC2SId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getC2SId() {
      return c2SId_;
    }
    
    // optional int64 s2cId = 2;
    public static final int S2CID_FIELD_NUMBER = 2;
    private long s2CId_;
    public boolean hasS2CId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getS2CId() {
      return s2CId_;
    }
    
    // optional string javaProtobufClassC2S = 3;
    public static final int JAVAPROTOBUFCLASSC2S_FIELD_NUMBER = 3;
    private java.lang.Object javaProtobufClassC2S_;
    public boolean hasJavaProtobufClassC2S() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getJavaProtobufClassC2S() {
      java.lang.Object ref = javaProtobufClassC2S_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          javaProtobufClassC2S_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getJavaProtobufClassC2SBytes() {
      java.lang.Object ref = javaProtobufClassC2S_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        javaProtobufClassC2S_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string javaProtobufClassS2C = 4;
    public static final int JAVAPROTOBUFCLASSS2C_FIELD_NUMBER = 4;
    private java.lang.Object javaProtobufClassS2C_;
    public boolean hasJavaProtobufClassS2C() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getJavaProtobufClassS2C() {
      java.lang.Object ref = javaProtobufClassS2C_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          javaProtobufClassS2C_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getJavaProtobufClassS2CBytes() {
      java.lang.Object ref = javaProtobufClassS2C_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        javaProtobufClassS2C_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes payload = 5;
    public static final int PAYLOAD_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString payload_;
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    
    private void initFields() {
      c2SId_ = 0L;
      s2CId_ = 0L;
      javaProtobufClassC2S_ = "";
      javaProtobufClassS2C_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, c2SId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, s2CId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getJavaProtobufClassC2SBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getJavaProtobufClassS2CBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, payload_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, c2SId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, s2CId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getJavaProtobufClassC2SBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getJavaProtobufClassS2CBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static microavatar.framework.base.protobuf.Base.Frame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static microavatar.framework.base.protobuf.Base.Frame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(microavatar.framework.base.protobuf.Base.Frame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements microavatar.framework.base.protobuf.Base.FrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return microavatar.framework.base.protobuf.Base.internal_static_Platform_Model_Frame_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return microavatar.framework.base.protobuf.Base.internal_static_Platform_Model_Frame_fieldAccessorTable;
      }
      
      // Construct using microavatar.framework.base.protobuf.Base.Frame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        c2SId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        javaProtobufClassC2S_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        javaProtobufClassS2C_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return microavatar.framework.base.protobuf.Base.Frame.getDescriptor();
      }
      
      public microavatar.framework.base.protobuf.Base.Frame getDefaultInstanceForType() {
        return microavatar.framework.base.protobuf.Base.Frame.getDefaultInstance();
      }
      
      public microavatar.framework.base.protobuf.Base.Frame build() {
        microavatar.framework.base.protobuf.Base.Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private microavatar.framework.base.protobuf.Base.Frame buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        microavatar.framework.base.protobuf.Base.Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public microavatar.framework.base.protobuf.Base.Frame buildPartial() {
        microavatar.framework.base.protobuf.Base.Frame result = new microavatar.framework.base.protobuf.Base.Frame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.c2SId_ = c2SId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2CId_ = s2CId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.javaProtobufClassC2S_ = javaProtobufClassC2S_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.javaProtobufClassS2C_ = javaProtobufClassS2C_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof microavatar.framework.base.protobuf.Base.Frame) {
          return mergeFrom((microavatar.framework.base.protobuf.Base.Frame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(microavatar.framework.base.protobuf.Base.Frame other) {
        if (other == microavatar.framework.base.protobuf.Base.Frame.getDefaultInstance()) return this;
        if (other.hasC2SId()) {
          setC2SId(other.getC2SId());
        }
        if (other.hasS2CId()) {
          setS2CId(other.getS2CId());
        }
        if (other.hasJavaProtobufClassC2S()) {
          setJavaProtobufClassC2S(other.getJavaProtobufClassC2S());
        }
        if (other.hasJavaProtobufClassS2C()) {
          setJavaProtobufClassS2C(other.getJavaProtobufClassS2C());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              c2SId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              s2CId_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              javaProtobufClassC2S_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              javaProtobufClassS2C_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 c2sId = 1;
      private long c2SId_ ;
      public boolean hasC2SId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getC2SId() {
        return c2SId_;
      }
      public Builder setC2SId(long value) {
        bitField0_ |= 0x00000001;
        c2SId_ = value;
        onChanged();
        return this;
      }
      public Builder clearC2SId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c2SId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 s2cId = 2;
      private long s2CId_ ;
      public boolean hasS2CId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getS2CId() {
        return s2CId_;
      }
      public Builder setS2CId(long value) {
        bitField0_ |= 0x00000002;
        s2CId_ = value;
        onChanged();
        return this;
      }
      public Builder clearS2CId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string javaProtobufClassC2S = 3;
      private java.lang.Object javaProtobufClassC2S_ = "";
      public boolean hasJavaProtobufClassC2S() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getJavaProtobufClassC2S() {
        java.lang.Object ref = javaProtobufClassC2S_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          javaProtobufClassC2S_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setJavaProtobufClassC2S(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        javaProtobufClassC2S_ = value;
        onChanged();
        return this;
      }
      public Builder clearJavaProtobufClassC2S() {
        bitField0_ = (bitField0_ & ~0x00000004);
        javaProtobufClassC2S_ = getDefaultInstance().getJavaProtobufClassC2S();
        onChanged();
        return this;
      }
      void setJavaProtobufClassC2S(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        javaProtobufClassC2S_ = value;
        onChanged();
      }
      
      // optional string javaProtobufClassS2C = 4;
      private java.lang.Object javaProtobufClassS2C_ = "";
      public boolean hasJavaProtobufClassS2C() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getJavaProtobufClassS2C() {
        java.lang.Object ref = javaProtobufClassS2C_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          javaProtobufClassS2C_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setJavaProtobufClassS2C(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        javaProtobufClassS2C_ = value;
        onChanged();
        return this;
      }
      public Builder clearJavaProtobufClassS2C() {
        bitField0_ = (bitField0_ & ~0x00000008);
        javaProtobufClassS2C_ = getDefaultInstance().getJavaProtobufClassS2C();
        onChanged();
        return this;
      }
      void setJavaProtobufClassS2C(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        javaProtobufClassS2C_ = value;
        onChanged();
      }
      
      // optional bytes payload = 5;
      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        payload_ = value;
        onChanged();
        return this;
      }
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000010);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Platform.Model.Frame)
    }
    
    static {
      defaultInstance = new Frame(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Platform.Model.Frame)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_Frame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_Frame_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ProtoFile/BaseFrame.proto\022\016Platform.Mo" +
      "del\"r\n\005Frame\022\r\n\005c2sId\030\001 \001(\003\022\r\n\005s2cId\030\002 \001" +
      "(\003\022\034\n\024javaProtobufClassC2S\030\003 \001(\t\022\034\n\024java" +
      "ProtobufClassS2C\030\004 \001(\t\022\017\n\007payload\030\005 \001(\014B" +
      "+\n#microavatar.framework.base.protobufB\004" +
      "Base"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_Model_Frame_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_Model_Frame_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_Frame_descriptor,
              new java.lang.String[] { "C2SId", "S2CId", "JavaProtobufClassC2S", "JavaProtobufClassS2C", "Payload", },
              microavatar.framework.base.protobuf.Base.Frame.class,
              microavatar.framework.base.protobuf.Base.Frame.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
